### ISSUE TITLE
Check for packages occurs too late to be helpful

### ISSUE THREAD

**Issue by jojo2357** [jojo2357/kiwix-zim#21]
Check packages is step 3 while `wget` is used in step 2 :flushed: They need to either swap or one needs to go away

**Comment by DocDrydenn** [comment]
To be honest, that package check function was only included because I wasn't sure what I was going to need when I was first writing the script... I borrowed it from a different script I wrote. If `wget` is all we "need", I suppose we could just get rid of the function as `wget` is pretty much standard on all distros.
